var builtInSets = [
	{ name: "Vambat", setName: "Mom", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Gnaw", move2: "Chomp", move3: "(No Move)", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Awakening", item: "none", level: 2, builtIn: true },
	{ name: "Eaglit", setName: "Mom", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Pounce", move2: "Shine", move3: "(No Move)", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Applied Frustration", item: "none", level: 3, builtIn: true },
	{ name: "Cathorn", setName: "Jeremy", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Bug Bite", move2: "Stare", move3: "Poison", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Defensive Priority", item: "none", level: 2, builtIn: true },
	{ name: "Nukichi", setName: "Jeremy", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Stupefy", move2: "Bulk Up", move3: "Impersonate", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Lucky", item: "none", level: 3, builtIn: true },
	{ name: "Twilat", setName: "Daniel", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Gnaw", move2: "Stretch", move3: "(No Move)", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Neutralize", item: "none", level: 4, builtIn: true },
	{ name: "Twittle", setName: "Shana", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Thunder Crash", move2: "Rogue Assault", move3: "(No Move)", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Mad Cap", item: "none", level: 3, builtIn: true },
	{ name: "Cathorn", setName: "Shana", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Counter Poise", move2: "Dodge", move3: "(No Move)", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Hasty", item: "none", level: 4, builtIn: true },
	{ name: "Cynamoth", setName: "Eric", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Counter Poise", move2: "Pestilence", move3: "Poison", move4: "Air Blade" }, posNature: "nimble", negNature: "smart", veryNature: "vFrail", ability: "Mystery Toxins", item: "Milkshake", level: 35, builtIn: true },
	{ name: "Avitross", setName: "Eric", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Nosedive", move2: "Thunder Crash", move3: "Perch", move4: "Driving Force" }, posNature: "brawny", negNature: "nimble", veryNature: "vClumsy", ability: "Madcap", item: "Health Amulet", level: 35, builtIn: true },
	{ name: "Tiklipse", setName: "Eric", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Gloominous Fangs", move2: "Radiant Rush", move3: "Chase Down", move4: "Quick Pounce" }, posNature: "brawny", negNature: "nimble", veryNature: "vClumsy", ability: "Total Eclipse", item: "Light Essence", level: 4, builtIn: true },
	{ name: "Bunpuff", setName: "Lucy *Route 1*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Petal Pummel", move2: "Gnaw", move3: "Mud Spatter", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Adorable", item: "none", level: 3, builtIn: true },
	{ name: "Kittone", setName: "Lucy *Route 1*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Tail Slap", move2: "Preemptive Strike", move3: "Tone Barrier", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Adorable", item: "none", level: 3, builtIn: true },
	{ name: "Kleptyke", setName: "Lucy *Route 1*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Chomp", move2: "Chase Down", move3: "Preemptive Strike", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Ability Thief", item: "none", level: 5, builtIn: true },
	{ name: "Phancub-Valentine", setName: "Lucas *Route 1*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Heart Break", move2: "Shadow Sprint", move3: "Final Ruse", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Ignorant", item: "none", level: 3, builtIn: true },
	{ name: "Burroach", setName: "Lucas *Route 1*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Barbs", move2: "Body Crash", move3: "Burrow", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Trash Armor", item: "none", level: 3, builtIn: true },
	{ name: "Geklow", setName: "Lucas *Route 1*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Luster Loot", move2: "Rejuvenate", move3: "Static Shock", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Radiance", item: "none", level: 5, builtIn: true },
	{ name: "Goswing", setName: "Carl", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Empathize", move2: "Preemptive Strike", move3: "Baffle", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Compliant", item: "Clutch Plushie", level: 1, builtIn: true },
	{ name: "Llamba", setName: "Carl", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Spit", move2: "Boom Bash", move3: "Energy Break", move4: "Raging Howl" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Regurgitate", item: "none", level: 5, builtIn: true },
	{ name: "Icigool", setName: "Nova", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Bag of Tricks", move2: "Barter", move3: "(No Move)", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Expertise", item: "Iciburst", level: 10, builtIn: true },
	{ name: "Icigool-Incarnate", setName: "Nova", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Bag of Tricks", move2: "Barter", move3: "(No Move)", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Expertise", item: "Iciburst", level: 10, builtIn: true },
	{ name: "Kayute", setName: "Stu", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Barbs", move2: "Spike Rush", move3: "Baffle", move4: "Gnarly Gash" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Designated Chompers", item: "none", level: 10, builtIn: true },
	{ name: "Kramboss", setName: "Stu", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Primal Slash", move2: "Ice Hammer", move3: "Bamboozle", move4: "Spike Rush" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Battle Armor", item: "Kramburst", level: 20, builtIn: true },
	{ name: "Kramboss-Frostshackled", setName: "Stu", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Primal Slash", move2: "Ice Hammer", move3: "Bamboozle", move4: "Spike Rush" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Battle Armor", item: "Kramburst", level: 20, builtIn: true },
	{ name: "Kayappa", setName: "Stu", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Bamboozle", move2: "Baffle", move3: "Ice Hammer", move4: "Spike Rush" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Ravenous", item: "none", level: 16, builtIn: true },
	{ name: "Kyeggo", setName: "Melissa", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Rant", move2: "Mud Spatter", move3: "Dark Surge", move4: "Nab" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Vicious", item: "Virulent Fang", level: 15, builtIn: true },
	{ name: "Doreggo", setName: "Melissa", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Shrewd Blast", move2: "Mud Spatter", move3: "Rant", move4: "Dark Surge" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Anomaly", item: "none", level: 32, builtIn: true },
	{ name: "Dreggodyne", setName: "Melissa", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Egg Storm", move2: "Air Blade", move3: "Mud Spatter", move4: "Shrewd Blast" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Staunch", item: "Dreggoburst", level: 35, builtIn: true },
	{ name: "Dreggodyne-Tempereign", setName: "Melissa", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Egg Storm", move2: "Air Blade", move3: "Mud Spatter", move4: "Shrewd Blast" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Staunch", item: "Dreggoburst", level: 35, builtIn: true },
	{ name: "Impkin", setName: "Terry", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Scapegoat", move2: "Tribute", move3: "Bag of Tricks", move4: "Memorize" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Handy", item: "none", level: 20, builtIn: true },
	{ name: "Grimmick", setName: "Terry", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Dark Surge", move2: "Slap Down", move3: "Splitting Headache", move4: "Barter" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Resentful", item: "Volcanic Ash", level: 32, builtIn: true },
	{ name: "Imperior", setName: "Terry", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Savage Horn", move2: "Tricky Tactics", move3: "Chase Down", move4: "Primal Slash" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Devious", item: "Imperiburst", level: 40, builtIn: true },
	{ name: "Imperior-Archfiend", setName: "Terry", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Savage Horn", move2: "Tricky Tactics", move3: "Chase Down", move4: "Primal Slash" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Devious", item: "Imperiburst", level: 40, builtIn: true },
	{ name: "Grubby", setName: "Kade", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Gnaw", move2: "Bug Bite", move3: "Baneful Bash", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Odd Husk", item: "none", level: 4, builtIn: true },
	{ name: "Antsee", setName: "Kade", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Bug Bite", move2: "Life Drain", move3: "Poison", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Drainage", item: "none", level: 4, builtIn: true },
	{ name: "Spirivii", setName: "Kade", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Bug Bite", move2: "Startle", move3: "Counter Poise", move4: "Driving Force" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Life Force", item: "none", level: 6, builtIn: true },
	{ name: "Pyder", setName: "John", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Counter Poise", move2: "Sting", move3: "Bug Bite", move4: "Mudslide" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Webbing", item: "none", level: 5, builtIn: true },
	{ name: "Pyder", setName: "John", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Baneful Bash", move2: "Vital Jab", move3: "Mega Chomp", move4: "Bug Bite" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Coursing Venom", item: "none", level: 5, builtIn: true },
	{ name: "Propae", setName: "Tyler", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Brace", move2: "Bug Bite", move3: "Poison", move4: "Pestilence" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Defensive Priority", item: "none", level: 10, builtIn: true },
	{ name: "Duskit", setName: "Corrupted Duskit", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Flabbergast", move2: "Dark Surge", move3: "Spectral Burst", move4: "Shadow Sprint" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Mean Spirited", item: "Volcanic Ash", level: 7, builtIn: true },
	{ name: "Swirelle", setName: "Alice", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Swat", move2: "Air Shot", move3: "Mud Spatter", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Appetite", item: "Health Amulet", level: 11, builtIn: true },
	{ name: "Banooh", setName: "Alice", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Chase Down", move2: "Raging Tackle", move3: "(No Move)", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Berserk", item: "none", level: 11, builtIn: true },
	{ name: "Operaptor", setName: "Vinegar", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Clamp", move2: "Chomp", move3: "Mud Spatter", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Terrifying", item: "Health Amulet", level: 7, builtIn: true },
	{ name: "Ceratot", setName: "Vinegar", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Outburst", move2: "Rogue Assault", move3: "Vine Lash", move4: "Mud Spatter" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Frail Armor", item: "Rageful Plushie", level: 10, builtIn: true },
	{ name: "Phancub", setName: "Vinegar", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Quick Punch", move2: "Shadow Sprint", move3: "Slap Down", move4: "(No Move)" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Sharp Claws", item: "Martial Shell", level: 13, builtIn: true },
	{ name: "Bunpuff", setName: "Lucy & Lucas *Gale Forest*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Petal Pummel", move2: "Timber Thrash", move3: "Quicksand", move4: "Swat" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Adorable", item: "none", level: 10, builtIn: true },
	{ name: "Kittone", setName: "Lucy & Lucas *Gale Forest*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Tail Slap", move2: "Preemptive Strike", move3: "Tone Barrier", move4: "Hullabaloo" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Adorable", item: "none", level: 10, builtIn: true },
	{ name: "Kleptyke", setName: "Lucy & Lucas *Gale Forest*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Chomp", move2: "Chase Down", move3: "Preemptive Strike", move4: "Hop Kick" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Ability Thief", item: "Shade Shell", level: 12, builtIn: true },
	{ name: "Phancub-Valentine", setName: "Lucy & Lucas *Gale Forest*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Heart Break", move2: "Shadow Sprint", move3: "Final Ruse", move4: "Slap Down" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Ignorant", item: "none", level: 10, builtIn: true },
	{ name: "Burroach", setName: "Lucy & Lucas *Gale Forest*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Slap Down", move2: "Body Crash", move3: "Burrow", move4: "Mud Spatter" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Trash Armor", item: "none", level: 10, builtIn: true },
	{ name: "Eleguana", setName: "Lucy & Lucas *Gale Forest*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Luster Loot", move2: "Rejuvenate", move3: "Magnify", move4: "Zip-Zap" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Raidance", item: "none", level: 12, builtIn: true },
	{ name: "Kayute", setName: "Lucy & Lucas *Gale Forest*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Stretch", move2: "Bulk Up", move3: "Spike Rush", move4: "Gnarly Gash" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Playful", item: "none", level: 10, builtIn: true },
	{ name: "Kyeggo", setName: "Terry *Gale Forest*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Mud Spatter", move2: "Dark Surge", move3: "Peace of Mind", move4: "Dodge" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Vicious", item: "Virulent Fang", level: 10, builtIn: true },
	{ name: "Impkin", setName: "Terry *Gale Forest*", evs: { hp: 0, energy: 0, attack: 0, defense: 0, attackR: 0, defenseR: 0, speed: 0 }, ivs: { hp: 40, energy: 40, attack: 40, defense: 40, attackR: 40, defenseR: 40, speed: 40 }, moves: { move1: "Dark Surge", move2: "Splitting Headache", move3: "Dodge", move4: "Peace of Mind" }, posNature: "none", negNature: "none", veryNature: "none", ability: "Devious", item: "none", level: 12, builtIn: true },
	
];
















